spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/community
    username: root
    password: root
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true

jwt:
  prefix: Bearer
  header: Authorization
  access-token: 7200000   #2시간
  secret : community