version: "3"

services:
  community-db:
    platform: linux/x86_64
    image: arm64v8/mysql:8.0.31
    container_name: community-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: community
    ports:
      - "3309:3306"
    volumes:
      - ../community-mysql:/var/lib/mysql
      - ../community-mysql-conf:/etc/mysql/conf.d
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
